# Generated by Django 3.0 on 2020-04-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200, null=True)),
                ('LastName', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=200, null=True, unique=True)),
                ('Notes', models.TextField(max_length=500, null=True)),
                ('Enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Promo', 'Promo'), ('Notification', 'Notification')], max_length=200, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Display', models.CharField(max_length=200, null=True)),
                ('MessageText', models.TextField(max_length=500, null=True)),
                ('Discount', models.BooleanField(default=False)),
                ('DiscountType', models.CharField(choices=[('Percent', 'Percent'), ('Money', 'Money')], max_length=200, null=True)),
                ('DiscountAmount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.Customer')),
                ('Message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.Message')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Tags',
            field=models.ManyToManyField(to='Web.Tag'),
        ),
    ]
